package ca.douglascollege.flamingdodos.realestate.forms;

import ca.douglascollege.flamingdodos.realestate.data.NewCenturyDatabase;
import ca.douglascollege.flamingdodos.realestate.data.models.AgentModel;
import ca.douglascollege.flamingdodos.realestate.data.models.SaleTransactionModel;
import ca.douglascollege.flamingdodos.realestate.generator.CommissionSlipGenerator;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.tmatesoft.sqljet.core.SqlJetException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CommissionSlip extends BaseOutputForm {
    private JPanel contentPane;
    private JTextArea commissionText;
    private JButton closeButton;
    private JButton printButton;

    public CommissionSlip(SaleTransactionModel transactionModel) {
        try {
            AgentModel agent = transactionModel
                    .getPropertyListing(NewCenturyDatabase.getInstance().getPropertyListingService())
                    .getAgent(NewCenturyDatabase.getInstance().getAgentService());

            setTitle("Commission Slip for " + agent.firstName + " " + agent.lastName);

            init(commissionText, new CommissionSlipGenerator(transactionModel));
        } catch (SqlJetException e) {
            e.printStackTrace();
        }

        setContentPane(contentPane);

        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                close();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        commissionText = new JTextArea();
        commissionText.setEditable(false);
        commissionText.setFont(new Font("Courier New", commissionText.getFont().getStyle(), commissionText.getFont().getSize()));
        commissionText.setText("New Century Realty Company\n\nCommission Slip for {AGENT_NAME}\n\nFirst $100,000 - 8%\t\t\t\t{FIRST_100K}\nRemaining Value - 3%\t\t\t\t{REMAINING}\n------------------------------------------------------------\nSubtotal\t\t\t\t\t{SUB_TOTAL}\n\nGST - 5%\t\t\t\t\t{GST}\nDeal Fee\t\t\t\t\t-{DEAL_FEE}\n------------------------------------------------------------\nTotal\t\t\t\t\t\t{COMMISSION}");
        contentPane.add(commissionText, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        contentPane.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        printButton = new JButton();
        printButton.setHorizontalTextPosition(0);
        printButton.setText("Print");
        panel1.add(printButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        panel1.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
