package ca.douglascollege.flamingdodos.realestate.forms;

import javax.swing.*;
import java.awt.*;

public class CommissionSlip extends BaseForm {
    private JPanel contentPane;
    private JTextArea commissionText;
    private JButton closeButton;
    private JButton printButton;

    public CommissionSlip() {
        super("Commission Slip for {AGENT_NAME}");

        setContentPane(contentPane);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        commissionText = new JTextArea();
        commissionText.setEditable(false);
        commissionText.setFont(new Font("Courier New", commissionText.getFont().getStyle(), commissionText.getFont().getSize()));
        commissionText.setText("New Century Realty Company\n\nCommission Slip for {AGENT_NAME}\n\nFirst $100,000 - 8%\t\t\t\t{FIRST_100K}\nRemaining Value - 3%\t\t\t\t{REMAINING}\n------------------------------------------------------------\nSubtotal\t\t\t\t\t{SUB_TOTAL}\n\nGST - 5%\t\t\t\t\t{GST}\nDeal Fee\t\t\t\t\t-{DEAL_FEE}\n------------------------------------------------------------\nTotal\t\t\t\t\t\t{COMMISSION}");
        contentPane.add(commissionText, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        contentPane.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        printButton = new JButton();
        printButton.setHorizontalTextPosition(0);
        printButton.setText("Print");
        panel1.add(printButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        panel1.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
