package ca.douglascollege.flamingdodos.realestate.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SellerStatement extends BaseForm {
    private JTextArea commissionText;
    private JButton printButton;
    private JButton closeButton;
    private JPanel contentPane;

    public SellerStatement() {
        super("Seller Statement");

        setContentPane(contentPane);
        closeButton.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e) {
                close();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        commissionText = new JTextArea();
        commissionText.setEditable(false);
        commissionText.setFont(new Font("Courier New", commissionText.getFont().getStyle(), commissionText.getFont().getSize()));
        commissionText.setText("New Century Realty Company\n\nSeller Statement\n\nSelling Price\t\t\t\t\t{PRICE}\nAgent Commission Fee\t\t\t\t-{AGENT_FEE}\n------------------------------------------------------------\nTotal\t\t\t\t\t\t{TOTAL}");
        contentPane.add(commissionText, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        contentPane.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        printButton = new JButton();
        printButton.setHorizontalTextPosition(0);
        printButton.setText("Print");
        panel1.add(printButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        panel1.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
